package application.liedetector.uicore.theme.tokens

enum class DimenToken {
    MAIN_PADDING,    // Standard padding for screens
    WIDGET_SPACING,  // Space between cards
    CORNER_RADIUS,   // "Material 3" or "iOS Rounded"
    ICON_SIZE_NAV,
    ICON_SIZE_SMALL,
    ICON_SIZE_TINY,
    ICON_SIZE_LARGE,
    HEADER_HEIGHT,
    
    DRAWER_CORNER,
    WIDGET_CORNER,
    BUTTON_HEIGHT,
    
    SPACING_TINY,
    SPACING_SMALL,
    SPACING_MEDIUM,
    SPACING_LARGE,
    SPACING_XL,
    
    PADDING_ERROR,
    PADDING_LOADING,
    
    PARALLAX_INTENSITY,
    MAX_CONTENT_WIDTH,
    
    LOADING_INDICATOR_SIZE,
    LOADING_INDICATOR_STROKE,
    
    // Feature specific
    WELCOME_MIN_HEIGHT,
    SUBJECT_CARD_WIDTH,
    SUBJECT_CARD_HEIGHT,
    SUBJECT_CARD_ICON_SIZE,
    
    SUBJECT_STORY_WIDTH,
    SUBJECT_STORY_HEIGHT,
    SUBJECT_ROW_HEIGHT,
    AVATAR_SIZE_SMALL,
    
    // Background Grid
    BACKGROUND_CELL_WIDTH,
    BACKGROUND_CELL_HEIGHT,

    // Selection & Indicators
    SELECTION_INDICATOR_WIDTH,
    CHECKMARK_SIZE_SMALL,
    DIVIDER_THICKNESS,
    DRAWER_WIDTH,

    // Recorder specific
    RECORDER_SHEET_PEEK,
    RECORDER_DRAG_HANDLE_WIDTH,
    RECORDER_DRAG_HANDLE_HEIGHT,
    RECORDER_WAVEFORM_STEP,
    RECORDER_WAVEFORM_BAR_WIDTH,
    RECORDER_WAVEFORM_MIN_HEIGHT,
    RECORDER_WAVEFORM_HEIGHT,
    RECORDER_CONTROL_SPACING,
    RECORDER_RULER_TICK_LARGE,
    RECORDER_RULER_TICK_SMALL,
    RECORDER_RULER_TEXT_SIZE,

    // Typography (Relative scale)
    TEXT_SIZE_TITLE_LARGE,   // ~42sp
    TEXT_SIZE_TITLE_MEDIUM,  // ~18sp
    TEXT_SIZE_TITLE_SMALL,   // ~17sp
    TEXT_SIZE_BODY,          // ~14sp
    TEXT_SIZE_CAPTION        // ~13sp
}
