package application.liedetector.uicore.theme.tokens

enum class StringToken {
    APP_NAME,
    WELCOME_TEXT,
    SUBJECT_NEW_TITLE,
    SUBJECT_NEW_BUTTON,
    DRAWER_SETTINGS,
    DRAWER_DARK_MODE,
    
    // Error States
    ERROR_NO_INTERNET_TITLE,
    ERROR_NO_INTERNET_MSG,
    ERROR_SERVER_TITLE,
    ERROR_SERVER_MSG,
    ERROR_UNKNOWN_TITLE,
    ERROR_UNKNOWN_MSG,
    ERROR_RETRY,
    
    // Toast Notifications
    TOAST_AUTH_SUCCESS,
    TOAST_AUTH_FAILED,
    TOAST_GENERIC_WARNING,

    // UI Elements
    RECORD,
    ANALYSIS_SCORE,
    UNKNOWN_WIDGET,
    MENU,
    CLOSE,

    // Debug Dashboard
    DEBUG_TITLE,
    DEBUG_TRIGGER_LOADING,
    DEBUG_TRIGGER_ERROR_BLOCKING,
    DEBUG_TRIGGER_ERROR_TOAST,
    DEBUG_TRIGGER_SUCCESS_TOAST,

    DEBUG_DASHBOARD,
    TAB_STATES,
    TAB_WIDGETS,
    TAB_LABS,
    OPEN_DEBUG_SANDBOX,
    LABS_EMPTY_MESSAGE,
    RECORDING_SCREEN_PLACEHOLDER,
    RECORDING_SCREEN_TITLE,
    DELETE_RECORDING_CONFIRMATION,
    
    SECTION_TEMPLATES,
    SECTION_RECORDINGS,
    
    // Drawer
    DRAWER_FOOTER_TITLE,
    DRAWER_FOOTER_SUBTITLE
}
