# Kotlin
kotlin.code.style=official

# Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.daemon=true

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
