package application.poligraf.ui.theme.tokens

enum class StringToken {
    // Common
    APP_NAME,
    WELCOME_1,
    WELCOME_2,
    WELCOME_3,
    WELCOME_4,
    SETTINGS,
    CLOSE,
    HISTORY,
    DARK_MODE,
    FOOTER_TITLE,
    FOOTER_SUBTITLE,
    SAVE,
    DELETE,

    // Errors
    ERROR_TITLE,
    ERROR_MESSAGE,
    RETRY,

    // Recorder / Analyzer
    RECORDER_TITLE,
    ACTIVE_SESSION,
    SKIN_STATE_MAP,
    SKIN_VOICE_RIBBON,
    SKIN_EQUALIZER,
    SKIN_RINGS,

    LABEL_STRESS,
    LABEL_PRESSURE,
    LABEL_FEAR,
    LABEL_ZERO,
    LABEL_SYNC_ZONE,
    TIMELINE_TITLE,

    INTERPRETATION_CALM,
    INTERPRETATION_PANIC,
    INTERPRETATION_AGGRESSION,
    INTERPRETATION_CONFRONTATION,
    INTERPRETATION_DISORGANIZATION,
    INTERPRETATION_ANALYZING,
    INTERPRETATION_FORMAT,

    METRIC_JITTER,
    METRIC_PITCH,
    METRIC_RMS,

    // Debug
    DEBUG_TITLE,
    DEBUG_TRIGGER_LOADING,
    DEBUG_TRIGGER_ERROR,
    DEBUG_TRIGGER_SUCCESS
}
