package application.poligraf.ui.theme.tokens

enum class StringToken {
    // Common
    APP_NAME,
    WELCOME_1,
    WELCOME_2,
    WELCOME_3,
    WELCOME_4,
    SETTINGS,
    CLOSE,
    HISTORY,
    DARK_MODE,
    FOOTER_TITLE,
    FOOTER_SUBTITLE,
    SAVE,
    DELETE,

    // Errors
    ERROR_TITLE,
    ERROR_MESSAGE,
    RETRY,

    // Recorder / Analyzer
    ANALYZER_TITLE,
    ACTIVE_SESSION,
    ANALYSIS_SYNTHESIZING,
    SKIN_STATE_MAP,
    SKIN_VOICE_RIBBON,
    SKIN_EQUALIZER,
    SKIN_RINGS,

    LABEL_SYNC_ZONE,
    TIMELINE_TITLE,

    // Continuous Live Statuses & Guidance
    STATUS_WARMUP,
    STATUS_CLIPPING,
    STATUS_LOW_SNR,
    STATUS_CALM,
    STATUS_MILD_FLUCTUATION,
    STATUS_FEAR_SINGLE,
    STATUS_STRESS_SINGLE,
    STATUS_PRESSURE_SINGLE,

    INTERPRETATION_CALM,
    INTERPRETATION_PANIC,
    INTERPRETATION_AGGRESSION,
    INTERPRETATION_CONFRONTATION,
    INTERPRETATION_DISORGANIZATION,
    INTERPRETATION_ANALYZING,
    INTERPRETATION_FORMAT,

    METRIC_JITTER,
    METRIC_PITCH,
    METRIC_RMS,

    // Debug
    DEBUG_TITLE,
    DEBUG_TRIGGER_LOADING,
    DEBUG_TRIGGER_ERROR,
    DEBUG_TRIGGER_SUCCESS,

    // History
    HISTORY_EMPTY,
    HISTORY_ITEM_MARKERS,
    HISTORY_ITEM_NOTES,
    HISTORY_SUMMARY_VOLATILITY,
    HISTORY_SUMMARY_DURATION,
    HISTORY_SUMMARY_MARKERS,
    VOLATILITY_LOW,
    VOLATILITY_MEDIUM,
    VOLATILITY_HIGH,
    CONCLUSION_POSITIVE,
    CONCLUSION_NEGATIVE,
    CONCLUSION_NEUTRAL,
    CONCLUSION_UNRELIABLE,
    LABEL_NOTES,
    NOTES_HINT,
    HISTORY_DETAIL_TITLE,
    SESSION_INDEX_FORMAT,

    // Settings
    SETTINGS_PREFERENCES_TITLE,
    SETTINGS_SKIN_TITLE,
    SETTINGS_MARKER_TITLE,
    SETTINGS_QUANTUM_WINDOW_TITLE,
    SETTINGS_SENSITIVITY_TITLE,
    SENSITIVITY_LOW,
    SENSITIVITY_MEDIUM,
    SENSITIVITY_HIGH
}
